# Generated by Django 4.2.8 on 2023-12-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="voter", name="ip_address",),
        migrations.AlterField(
            model_name="poll", name="date", field=models.DateField(auto_now_add=True),
        ),
    ]
